services:
  dmss:
    image: datamodelingtool.azurecr.io/dmss:${DMSS_TAG:-latest}
    platform: linux/amd64
    restart: unless-stopped
    environment:
      AUTH_ENABLED: 0
      REDIS_PASSWORD: maf
      MONGO_PASSWORD: maf
      ENVIRONMENT: ${ENVIRONMENT:-local}
      RESET_DATA_SOURCE: "off"
      SECRET_KEY: sg9aeUM5i1JO4gNN8fQadokJa3_gXQMLBjSGGYcfscs= # Don't reuse this in production...
#    volumes:
#      - ../../data-modelling-storage-service/src:/code/src
    ports:
      - '5000:5000'
    depends_on:
      - db
      - redis

  db:
    image: mongo:3.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: maf
      MONGO_INITDB_ROOT_PASSWORD: maf
    volumes:
      - ./dmss-data/db:/data/db

  job-api:
    image: datamodelingtool.azurecr.io/dm-job:${JOB_API_TAG:-latest}
    platform: linux/amd64
    restart: unless-stopped
    environment:
      SCHEDULER_ENVS_TO_EXPORT: 'PUBLIC_DMSS_API,SIMA_LICENSE'
      SCHEDULER_REDIS_HOST: redis
      SCHEDULER_REDIS_PASSWORD: maf
      DMSS_API: http://dmss:5000
      AUTH_ENABLED: 0
      ENVIRONMENT: local
      AZURE_JOB_SUBSCRIPTION: 14d57366-b2ae-4da8-8b75-e273c6fdabe2
      AZURE_JOB_RESOURCE_GROUP: dmt-test-containers
      AZURE_SP_SECRET: ${AZURE_SP_SECRET}
      AZURE_JOB_TENANT_ID: 3aa4a235-b6e2-48d5-9195-7fcf05b459b0
      AZURE_JOB_CLIENT_ID: 97a6b5bd-63fb-42c6-bb75-7e5de2394ba0
      MONGO_PASSWORD: maf
      #SIMA_LICENSE: |
    depends_on:
      - redis
      - db
    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock # Needed for docker-in-docker jobs
      - ./job_handlers:/code/src/job_handler_plugins
#      - ../../dm-job/src/job_handler_plugins:/code/src/job_handler_plugins
#      - ../../dm-job/src:/code/src
    ports:
      - '5001:5000'

  #  db-ui:
  #    image: mongo-express:1.0.0-alpha
  #    restart: unless-stopped
  #    ports:
  #      - "8082:8081"
  #    environment:
  #      ME_CONFIG_MONGODB_SERVER: db
  #      ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #      ME_CONFIG_MONGODB_ADMINPASSWORD: xd7wCEhEx4kszsecYFfC
  #      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"

  redis:
    image: bitnami/redis:latest
    environment:
      REDIS_PASSWORD: maf
      #    volumes:
      #     - ./dmss-data/redis:/bitnami