version: '3.4'

services:
  dmss:
    image: datamodelingtool.azurecr.io/dmss:v1.16.2
    platform: linux/amd64
    restart: unless-stopped
    environment:
      AUTH_ENABLED: 0
      ENVIRONMENT: local
#      RESET_DATA_SOURCE: off
      MONGO_USERNAME: maf
      MONGO_PASSWORD: xd7wCEhEx4kszsecYFfC
      SECRET_KEY: sg9aeUM5i1JO4gNN8fQadokJa3_gXQMLBjSGGYcfscs= # Don't reuse this in production...
#    volumes:
#      - ../../data-modelling-storage-service/src:/code/src
    ports:
      - '5000:5000'
    depends_on:
      - db

  db:
    image: mongo:3.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: maf
      MONGO_INITDB_ROOT_PASSWORD: xd7wCEhEx4kszsecYFfC
    volumes:
      - ./dmss-data/db:/data/db

  job-api:
    image: datamodelingtool.azurecr.io/dm-job:v1.5.1
    platform: linux/amd64
    restart: unless-stopped
    environment:
      SCHEDULER_ENVS_TO_EXPORT: 'PUBLIC_DMSS_API,SIMA_LICENSE'
      SCHEDULER_REDIS_HOST: job-store
      SCHEDULER_REDIS_PORT: 6379
      SCHEDULER_REDIS_SSL: 'false'
      DMSS_API: http://dmss:5000
      API_DEBUG: 1
      AUTH_ENABLED: 0
      ENVIRONMENT: local
      AZURE_JOB_SUBSCRIPTION: 14d57366-b2ae-4da8-8b75-e273c6fdabe2
      AZURE_JOB_RESOURCE_GROUP: dmt-test-containers
      AZURE_SP_SECRET: ${AZURE_SP_SECRET}
      AZURE_JOB_TENANT_ID: 3aa4a235-b6e2-48d5-9195-7fcf05b459b0
      AZURE_JOB_CLIENT_ID: 97a6b5bd-63fb-42c6-bb75-7e5de2394ba0
      MONGO_PASSWORD: xd7wCEhEx4kszsecYFfC
      #SIMA_LICENSE: |
    depends_on:
      - job-store
      - db
    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock # Needed for docker-in-docker jobs
      - ./job_handlers:/code/src/job_handler_plugins
#      - ../../dm-job/src/job_handler_plugins:/code/src/job_handler_plugins
#      - ../../dm-job/src:/code/src
    ports:
      - '5001:5000'

  #  db-ui:
  #    image: mongo-express:1.0.0-alpha
  #    restart: unless-stopped
  #    ports:
  #      - "8082:8081"
  #    environment:
  #      ME_CONFIG_MONGODB_SERVER: db
  #      ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #      ME_CONFIG_MONGODB_ADMINPASSWORD: xd7wCEhEx4kszsecYFfC
  #      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"

  job-store:
    image: redis:6.2.5-alpine
    command: 'redis-server --save 30 1 --loglevel notice'
    #    volumes:
    #     - ./redis_data:/data
