repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: trailing-whitespace
        exclude: ^.*\.(lock)$||^docs\/
      - id: mixed-line-ending
        exclude: ^.*\.(lock)$||^docs\/
      - id: detect-private-key

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
        files: ^.*\.(ts|tsx|js|css|html|json)$
        args: ['--config=.prettierrc.js', '--ignore-path=.prettierignore']

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.38.0'
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - eslint
          - eslint-config-react-app
          - typescript
          - '@typescript-eslint/parser'
          - '@typescript-eslint/eslint-plugin'
          - eslint-config-prettier # turns off all rules that might conflict with prettier
          - eslint-plugin-jsx-a11y # checks accessibility rules on jsx elements
          - eslint-plugin-prettier # runs prettier as an eslint rule
          - eslint-plugin-react # react specific linting rules
          - eslint-plugin-react-hooks # enforces the rules of hooks
        args: ['--config=.eslintrc.json', '--ignore-path=.eslintignore']
