name: "Create release-please pull request"

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      releases_created:
        description: "If true, a release PR has been merged"
        value: ${{ jobs.release-please.outputs.releases_created }}
      tag_name:
        description: "The release tag. Ex v1.4.0"
        value: ${{ jobs.release-please.outputs.tag_name }}

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release

    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}