on:
  # Workflow dispatch is used for manual triggers
  workflow_dispatch:
  # Workflow call is used for called from another workflow
  workflow_call:
    outputs:
      dm_cli_version:
        description: 'DM CLI version used in test'
        value: ${{ jobs.integration-tests.outputs.dm_cli_version }}
      dmss_version:
        description: 'DMSS version used in test'
        value: ${{ jobs.integration-tests.outputs.dmss_version }}
      job_version:
        description: 'Job version used in test'
        value: ${{ jobs.integration-tests.outputs.job_version }}

jobs:
  integration-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: e2e/
    # Map a step output to a job output
    outputs:
      dm_cli_version: ${{ steps.dm_cli.outputs.version }}
      dmss_version: ${{ steps.dmss.outputs.dmss_version }}
      job_version: ${{ steps.dmss.outputs.job_version }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install daemon process manager
        run: npm install pm2 -g
        working-directory: ./

      - name: Install dependencies
        run: yarn install
        working-directory: ./

      - name: Build packages
        run: yarn build:packages
        working-directory: ./

      - name: Start example application
        run: pm2 start "yarn start:example" --name web --wait-ready --listen-timeout 10000 # wait for 10 seconds
        working-directory: ./

      - name: Pull docker images
        run: docker-compose pull
        working-directory: example/

      - name: Capture output DMSS version
        run: |
          docker-compose run --rm dmss cat src/version.txt > dmss_version.txt
          dmss_version=$(tail -n 1 dmss_version.txt)
          echo "dmss_version=$dmss_version" >> "$GITHUB_OUTPUT"
        working-directory: example/

      - name: Capture job-api version
        run: |
          docker-compose run --rm job-api cat version.txt > job_version.txt
          job_version=$(tail -n 1 job_version.txt)
          echo "job_version=$job_version" >> "$GITHUB_OUTPUT"
        working-directory: example/

      - name: Run docker images
        run: docker-compose up -d
        working-directory: example/

      - name: Run reset app script
        run: |
          sleep 60
          docker-compose run --rm dmss reset-app
        working-directory: example/

      - name: Pack core plugins
        run: npm pack @development-framework/dm-core-plugins
        working-directory: example/

      - name: Extract tarball
        run: tar -xzf development-framework-dm-core-plugins-*.tgz
        working-directory: example/

      - name: Create required directory in node_modules
        run: mkdir -p node_modules/@development-framework/
        working-directory: example/

      - name: Move package to directory in node_modules
        run: mv package/ node_modules/@development-framework/dm-core-plugins
        working-directory: example/

      - name: Setup Python virtual environment
        id: setup_venv
        run: python -m venv .venv
        working-directory: example/

      - name: Activate Python virtual environment
        run: source .venv/bin/activate
        working-directory: example/

      - name: Install dm-cli package
        run: pip install dm-cli
        working-directory: example/

      - name: Capture dm-cli version
        id: capture_version
        run: echo "version=$(dm --version)" >> "$GITHUB_OUTPUT"
        working-directory: example/

      - name: Run reset-all script
        run: |
          source .venv/bin/activate
          ./reset-all.sh validate-entities
        working-directory: example/

      - name: Install dependencies
        run: |
          npm install --package-lock-only
          npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          pm2 ps
          npx playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: e2e/test-results/
          retention-days: 30

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: e2e/playwright-report/
          retention-days: 30
