on:
  workflow_dispatch:
  delete:
    branches-ignore:
      - main
      - gh-pages
    tags-ignore:
      - v*

jobs:
  remove-integration-tests-reports:
    uses: ./.github/workflows/remove-integration-tests-report.yaml