on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml

  integration-tests:
    uses: ./.github/workflows/integration-tests.yaml

  publish-integration-tests-report:
    needs: integration-tests
    if: ${{ ! cancelled() }}
    uses: ./.github/workflows/publish-integration-tests-report.yaml
    with:
      dmss_version: ${{ needs.integration-tests.outputs.dmss_version }}
      dm_cli_version: ${{ needs.integration-tests.outputs.dm_cli_version }}
      job_version: ${{ needs.integration-tests.outputs.job_version }}
      update_readme: ${{ needs.integration-tests.result == 'success' }}

  release-please:
    needs: [tests, integration-tests]
    uses: ./.github/workflows/create-release-pr.yaml

  publish-packages:
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [dm-core, dm-core-plugins]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Create package distribution and publish
        run: |
          yarn install
          yarn build:packages
          yarn workspace @development-framework/dm-core publish --access public
          yarn workspace @development-framework/dm-core-plugins publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
