on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml

  integration-tests:
    uses: ./.github/workflows/integration-tests.yaml

  publish-integration-tests-report:
    needs: integration-tests
    if: ${{ ! cancelled() }}
    uses: ./.github/workflows/publish-integration-tests-report.yaml
    with:
      dmss_version: ${{ needs.integration-tests.outputs.dmss_version }}
      dm_cli_version: ${{ needs.integration-tests.outputs.dm_cli_version }}
      job_version: ${{ needs.integration-tests.outputs.job_version }}
      update_readme: ${{ needs.integration-tests.result == 'success' }}

  release-please:
    needs: [tests, integration-tests]
    uses: ./.github/workflows/create-release-pr.yaml

  publish-packages:
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install

      - name: Build packages
        run: yarn build:packages

      - name: Publish dm-core package
        run: |
          PACKAGE_VERSION=$(cat packages/dm-core/package.json | jq '.["version"]' | tr -d '"')
          PACKAGE_NAME=$(cat packages/dm-core/package.json | jq '.["name"]' | tr -d '"')
          VERSION_EXISTS=$(curl --HEAD --output /dev/null --silent -w "%{http_code}" https://registry.npmjs.org/$PACKAGE_NAME/$PACKAGE_VERSION)
          if [[ $VERSION_EXISTS == 404 ]]; then
            yarn workspace @development-framework/dm-core publish --access public
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish dm-core-plugins package
        run: |
          PACKAGE_VERSION=$(cat packages/dm-core-plugins/package.json | jq '.["version"]' | tr -d '"')
          PACKAGE_NAME=$(cat packages/dm-core-plugins/package.json | jq '.["name"]' | tr -d '"')
          VERSION_EXISTS=$(curl --HEAD --output /dev/null --silent -w "%{http_code}" https://registry.npmjs.org/$PACKAGE_NAME/$PACKAGE_VERSION)
          if [[ $VERSION_EXISTS == 404 ]]; then
            yarn workspace @development-framework/dm-core-plugins publish --access public
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  new-release:
    needs: publish-packages
    permissions:
      packages: write
      contents: read
      id-token: write
    uses: ./.github/workflows/on-release.yaml
    with:
      release-tag: ${{ needs.release-please.outputs.tag_name }}
