on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
      - gh-pages
    tags-ignore:
      - v*

concurrency:
  group: on-push-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml

  integration-tests:
    uses: ./.github/workflows/integration-tests.yaml

  publish-integration-tests-report:
    needs: integration-tests
    if: ${{ ! cancelled() }}
    uses: ./.github/workflows/publish-integration-tests-report.yaml
    with:
      dmss_version: ${{ needs.integration-tests.outputs.dmss_version }}
      dm_cli_version: ${{ needs.integration-tests.outputs.dm_cli_version }}
      job_version: ${{ needs.integration-tests.outputs.job_version }}
