on:
  # Workflow dispatch is used for manual triggers
  workflow_dispatch:
  # Workflow call is used for called from another workflow
  workflow_call:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files

  tests:
    strategy:
      matrix:
        package: [ dm-core, dm-core-plugins ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-node@v3

      # TODO: Cache yarn install

      - name: 'Install dependencies'
        run: yarn install

      - name: 'Build packages'
        run: yarn build:packages

      - name: 'Test packages'
        run: yarn test:packages
