on:
  # Workflow dispatch is used for manual triggers
  workflow_dispatch:
  # Workflow call is used for called from another workflow
  workflow_call:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run prettier formatting
        run: pre-commit run prettier --all-files

  tests:
    strategy:
      matrix:
        package: [ dm-core, dm-core-plugins ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-node@v3

      # TODO: Cache yarn install

      - name: "test"
        run: |
          cd packages/${{ matrix.package }}
          yarn install
          yarn tsc
          HAS_TESTS=$(cat package.json | jq '.["scripts"]["test"]')
          if [[ $HAS_TESTS != "null" ]]; then
            yarn test
          fi
