on:
  # Workflow dispatch is used for manual triggers
  workflow_dispatch:
  # Workflow call is used for called from another workflow
  workflow_call:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Cache pre-commit environment
        uses: actions/cache@v3
        env:
          cache-name: cache-pre-commit
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./.pre-commit-config.yaml')}}

      - name: Run pre-commit
        env:
          # These need node_modules, and will be covered in the build step anyway
          SKIP: type_check_core,type_check_plugins
        run: pre-commit run --all-files

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-node@v3

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ./node_modules
            ./example/node_modules
            ./packages/dm-core/node_modules
            ./packages/dm-core-plugins/node_modules
            ./yarn.lock
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./packages/dm-core/package.json')}}-${{ hashFiles('./packages/dm-core-plugins/package.json') }}

      - name: 'Install dependencies'
        run: yarn install

      - name: 'Build packages'
        run: yarn build:packages

      - name: 'Test packages'
        run: yarn test:packages
